language: node_js
node_js:
- '0.10'
script:
- npm run build && npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
- sudo apt-get update;
- sudo apt-get install gcc-4.8 g++-4.8;
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
- sudo g++ --version;
- sudo apt-get update -qq;
notifications:
  email: false
  slack:
    secure: EOZZJJboKX+qGE7nuAL2t0kbe0LDkmMLJ56oyDb6nOuaPTZ+YLrzXq+6H3OnPCDNH3qHna+dyG6AxsR7EbuBR/6bFUk4NE6Bq13iegZHlIdVsX0ZUmRMbhaRm8xbreU8NltFNN6xi/QN+zpNkHn8UmoX2sR+78OcDim7ACdbSLs=
